export const env = {
  PORT: Number(process.env.PORT) || 3000,
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
  JWT_SECRET: process.env.JWT_SECRET || "supersecret-key",
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || "7d",
  NODE_ENV: process.env.NODE_ENV || "development",
  AGENT_URL: process.env.AGENT_URL,
  CHAT_BOT_URL: process.env.CHAT_BOT_URL,
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASS: process.env.MAIL_PASS,
  CLIENT_URL: process.env.CLIENT_URL,
  DASHBOARD_URL: process.env.DASHBOARD_URL,
  MOMO_PARTNER_CODE: process.env.MOMO_PARTNER_CODE,
  MOMO_ACCESS_KEY: process.env.MOMO_ACCESS_KEY,
  MOMO_SECRET_KEY: process.env.MOMO_SECRET_KEY,
  MOMO_REDIRECT_URL: process.env.MOMO_REDIRECT_URL,
  MOMO_IPN_URL: process.env.MOMO_IPN_URL,
  MOMO_REQUEST_TYPE: process.env.MOMO_REQUEST_TYPE,
  MOMO_ENDPOINT: process.env.MOMO_ENDPOINT,
  TMN_CODE: process.env.TMN_CODE,
  SECURE_SECRET: process.env.SECURE_SECRET,
  VNPAY_HOST: process.env.VNPAY_HOST,
  VNPAY_RETURN_URL: process.env.VNPAY_RETURN_URL,
  VNPAY_IP_ADDRESS: process.env.VNPAY_IP_ADDRESS,
  REDIS_URL_BUSINESS: process.env.REDIS_URL_BUSINESS,
  REDIS_URL_CACHE: process.env.REDIS_URL_CACHE,
  RABBITMQ_URL: process.env.RABBITMQ_URL,
};
