export const PAYMENT_STATUS = {
    PENDING : "PENDING", 
    COMPLETED : "COMPLETED", 
    FAILED : "FAILED",
    CANCELED : "CANCELED", 
    REFUND_PENDING : "REFUND_PENDING", 
    REFUNDED : "REFUNDED"	
}
