export const STEPS = {
    SELECT_MOVIE : "SELECT_MOVIE",
    SELECT_SHOW_TIME : "SELECT_SHOW_TIME",
    SELECT_SHOW_TIME_SEATS : "SELECT_SHOW_TIME_SEATS",
    SELECT_ADDON : "SELECT_ADDON",
    SELECT_PAYMENT_METHOD : "SELECT_PAYMENT_METHOD"
}